# .github/workflows/ci.yml

name: CI

on:
  push:
    branches: [ main, github_actions ] # Trigger on push to main or master branch
  pull_request:
    branches: [ main, github_actions ] # Trigger on pull requests targeting main or master

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Run on a fresh Ubuntu virtual machine

    # Add PostgreSQL service
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: blog_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Action to checkout your repository code

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        # TODO how to fix this hardcoded python version
        python-version: '3.10' # Specify the Python version you want to use (e.g., '3.9', '3.10', '3.x')

    - name: Install uv
      run: pip install uv # Install uv globally or in a dedicated venv if preferred

    - name: Install dependencies with uv
      run: uv sync # Use uv sync to install dependencies based on pyproject.toml or requirements.txt

    - name: Run tests with pytest
      env: 
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: uv run -m pytest # Execute your pytest tests